FROM python:3.12-slim

WORKDIR /app
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY api/main.py .
COPY airflow/dags/mood_config.py dags/mood_config.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
