FROM apache/airflow:3.2.1-python3.12

USER airflow

RUN pip install --no-cache-dir \
    kaggle==1.6.17 \
    deltalake==0.25.5 \
    pandas==2.3.3 \
    s3fs==2026.4.0 \
    scikit-learn==1.6.1 \
    joblib==1.5.1 \
    requests==2.33.1 \
    psycopg2-binary==2.9.10 \
    feast[redis]==0.62.0 \
    && pip install --no-cache-dir "uvicorn>=0.37.0"

COPY --chown=airflow:root soundwave/ /opt/airflow/soundwave/
ENV PYTHONPATH="/opt/airflow:${PYTHONPATH}"
